const productList = [
  {
    id: 0,
    name: "Mocha Machiato",
    price: 9.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "./assest/Toffee-Nut-Cream-Cold-Brew-.jpeg",
  },
  {
    id: 1,
    name: "Caramel Machiato",
    price: 8.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "./assest/iced-caramel-macchiato.jpg",
  },
  {
    id: 2,
    name: "Peppermint Frappuchino",
    price: 10.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "./assest/Peppermint_Mocha.min-720x376.jpg",
  },
  {
    id: 3,
    name: "Coconut Mocha",
    price: 7.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "./assest/coconut.jpg",
  },
  {
    id: 4,
    name: "Caramel Frappucino",
    price: 12.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "./assest/Caramel-Frappuccino_0.jpeg",
  },
  {
    id: 5,
    name: "Cantaloupe Frappucino",
    price: 12.99,
    description: "Some quick example text to build on the card title",
    imgsScr:
      "/assest/cantaloupe-melon-cream-frappuccino-from-starbucks-philippines.webp",
  },
  {
    id: 6,
    name: "Matcha Frappucino",
    price: 10.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "/assest/SBX20181127_IcedMatchaGreenTeaLatte.jpeg",
  },
  {
    id: 7,
    name: "Melon Ice Tea",
    price: 8.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "/assest/melon.jpg",
  },
  {
    id: 8,
    name: "Mango Ice Tea",
    price: 8.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "/assest/SBX20190531_IcedBlackTea.jpeg",
  },
  {
    id: 9,
    name: "Mocha Coockie'n Cream",
    price: 12.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "/assest/Mocha_Cookie_Crumble.max-825x550.jpg",
  },
  {
    id: 10,
    name: "Matcha Cake",
    price: 5.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "/assest/pngtree-the-green-matcha-cake-image_13139415.png",
  },
  {
    id: 11,
    name: "Chiffon Cake",
    price: 6.99,
    description: "Some quick example text to build on the card title",
    imgsScr: "/assest/cake.jpg",
  },
];
